
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herrera
 */
public class Principal6 extends javax.swing.JFrame {

    /**
     * Creates new form Principal6
     */
    public Principal6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSueldoBase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLeyPublica = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMontoAPagar = new javax.swing.JTextField();
        cmbCalcular = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSeguroSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSeguroForzoso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCajaDeAhorro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 24)); // NOI18N
        jLabel1.setText("EMPRESA-DESCUENTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel2.setText("Sueldo Base");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, -1));
        getContentPane().add(txtSueldoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, -1));

        jLabel3.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel3.setText("Monto A Pagar ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(txtLeyPublica, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, -1));

        jLabel4.setFont(new java.awt.Font("JasmineUPC", 2, 18)); // NOI18N
        jLabel4.setText("Ley de Politica  1%");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));
        getContentPane().add(txtMontoAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 70, -1));

        cmbCalcular.setText("CALCULAR");
        cmbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 110, 40));

        cmbBorrar.setText("BORRAR");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 110, 40));

        jLabel5.setFont(new java.awt.Font("JasmineUPC", 2, 18)); // NOI18N
        jLabel5.setText(" Seguro Social 4% ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 20));
        getContentPane().add(txtSeguroSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        jLabel6.setFont(new java.awt.Font("JasmineUPC", 2, 18)); // NOI18N
        jLabel6.setText(" Seguro Forzoso 0.5%");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        getContentPane().add(txtSeguroForzoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 70, -1));

        jLabel7.setText("Caja de ahorro 5%");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 20));

        txtCajaDeAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajaDeAhorroActionPerformed(evt);
            }
        });
        getContentPane().add(txtCajaDeAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCalcularActionPerformed
        // TODO add your handling code here:
        
        String  num1, res,res1,res2,res3,res4,resa;
        
        double n1 = 0,resultado = 0;
        int op = 0, porcentaje = 1, porcentaje1= 4, porcentaje3 = 5,total,rs,sr,sf,ca;
        double porcentaje2 = 0.5, rel, rela, tota;
        
        
        
        if (txtSueldoBase.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el Sueldo base", "Error",JOptionPane.ERROR_MESSAGE);
        txtSueldoBase.requestFocusInWindow();
        } else {
        
            
        
        n1= Double.parseDouble(txtSueldoBase.getText());
       
        }
        
        
         
         rs = (int) (n1*0.01);
         res1= String.valueOf(rs);
         txtLeyPublica.setText(res1);
         
         sr = (int) (n1*0.04);
       
         res2= String.valueOf(sr);
         txtSeguroSocial.setText(res2);
         
         sf = (int) (n1*0.005);
        
         res3= String.valueOf(sf);
         txtSeguroForzoso.setText(res3);
         
         ca = (int) (n1*0.05);
        
         res4= String.valueOf(ca);
         txtCajaDeAhorro.setText(res4);
         
         
          rel = (int) (rs+sr+sf+ca);
         res= String.valueOf(rel);
         txtMontoAPagar.setText(res);
         
         rela = (n1 - rel);
         resa= String.valueOf(rela);
         txtMontoAPagar.setText(resa);
         
    }//GEN-LAST:event_cmbCalcularActionPerformed

    private void txtCajaDeAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajaDeAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCajaDeAhorroActionPerformed

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
        txtSueldoBase.setText("");
        txtLeyPublica.setText("");
        txtSeguroSocial.setText("");
        txtSeguroForzoso.setText ("");
        txtCajaDeAhorro.setText ("");
        txtMontoAPagar.setText ("");
                
                
        txtSueldoBase.requestFocusInWindow();
        
        
    }//GEN-LAST:event_cmbBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCajaDeAhorro;
    private javax.swing.JTextField txtLeyPublica;
    private javax.swing.JTextField txtMontoAPagar;
    private javax.swing.JTextField txtSeguroForzoso;
    private javax.swing.JTextField txtSeguroSocial;
    private javax.swing.JTextField txtSueldoBase;
    // End of variables declaration//GEN-END:variables
}
